export const FETCH_POLLS_START = 'FETCH_POLLS_START';
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS';
export const FETCH_POLLS_FAILED = 'FETCH_POLLS_FAILED';

export const ADD_ANSWER_START = 'ADD_ANSWER_START';
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS'
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const ADD_ANSWER_INIT = 'ADD_ANSWER_INIT';

export const SET_RESULTS = 'SET_RESULTS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';