export const FETCH_POLLS = 'FETCH_POLLS';
export const SET_POLLS = 'SET_POLLS';
export const ADD_ANSWER = 'ADD_ANSWER';
export const FETCH_RESULTS = 'FETCH_RESULTS';
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const FETCH_POLLS_FAILED = 'FETCH_POLLS_FAILED';
export const FETCH_RESULTS_FAILED = 'FETCH_RESULTS_FAILED';