export const FETCH_POLLS = 'FETCH_POLLS';
export const FETCH_POLLS_FAILED = 'FETCH_POLLS_FAILED';
export const SET_POLLS = 'SET_POLLS';

export const ADD_ANSWER_START = 'ADD_ANSWER_START';
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS'
export const ADD_ANSWER_FAILED = 'ADD_ANSWER_FAILED';
export const ADD_ANSWER_INIT = 'ADD_ANSWER_INIT';

export const FETCH_RESULTS_START = 'FETCH_RESULTS_START';
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_FAILED = 'FETCH_RESULTS_FAILED';